base_url = "https://sthasushant.com.np"
title = "sthasushant"
description = "AI Engineer | Deep Learning & ML Blog"
generate_feeds = true
build_search_index = false
compile_sass = true
minify_html = true

taxonomies = [
    { name = "tags" },
]

[extra.taxonomies]
sort_by = "page_count"
reverse = true

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "ayu-dark", filename = "syntax-theme-dark.css" },
  { theme = "ayu-light", filename = "syntax-theme-light.css" }
]

[extra]
toc = true
use_cdn = false
generate_tags = false
favicon = "/icons/moon.svg"
theme = "toggle"
fancy_code = true
dynamic_note = true
mathjax = true
mathjax_dollar_inline_enable = true
repo_url = "https://github.com/2eightsushant/"

menu = [
    { name = "Posts", url = "/posts", weight = 1 }
]

socials = [
    { name = "x", url = "https://x.com/2eightsushant", icon = "twitter" },
    { name = "github", url = "https://github.com/2eightsushant/", icon = "github" },
    { name = "linkedin", url = "https://www.linkedin.com/in/2eightsushant/", icon = "linkedin" }
]


stylesheets = [
    # "custom.css"
]


[search]
include_title = false
include_description = false
include_path = false
include_content = false
index_format = "elasticlunr_json"


[extra.analytics]
enabled = true

[extra.analytics.goatcounter]
user = "2eightsushant"
host = "goatcounter.com"
