# -------------------
# Site Basics
# -------------------
base_url = "https://sthasushant.com.np"
title = "sthasushant"
description = "AI Engineer | Deep Learning & ML Blog"
generate_feeds = true
build_search_index = true
compile_sass = true
minify_html = true

taxonomies = [
    { name = "tags" },
]

[extra.taxonomies]
sort_by = "page_count"
reverse = true

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "ayu-dark", filename = "syntax-theme-dark.css" },
  { theme = "ayu-light", filename = "syntax-theme-light.css" }
]

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"              # light, dark, auto, toggle
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true
repo_url = "https://github.com/2eightsushant/"

menu = [
    { name = "Posts", url = "/posts", weight = 1 }
]

socials = [
    { name = "x", url = "https://x.com/2eightsushant", icon = "twitter" },
    { name = "github", url = "https://github.com/2eightsushant/", icon = "github" },
    { name = "linkedin", url = "https://linkedin.com/2eightsushant/", icon = "linkedin" }
]


stylesheets = [
    # "custom.css"
]


[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"


[extra.analytics]
enabled = false

[extra.analytics.goatcounter]
user = "your_user"
host = "example.com"
